Repository NixOS/SC-election-2024, pull requests merged in 2024-09, with the labels that each got.

#22 Nominate doronbehar
  candidates/doronbehar.md
Labels: nomination

#38 Nominate scrumplex
  candidates/scrumplex.md
Labels: nomination

#41 Nominate tomberek
  candidates/tomberek.md
Labels: nomination, enough endorsements

#49 Nominate kloenk
  candidates/kloenk.md
Labels: nomination

#65 Ericson2314 self-nominate
  candidates/Ericson2314.md
Labels: nomination, enough endorsements

#40 Nominate cafkafk
  candidates/cafkafk.md
Labels: nomination, enough endorsements

#54 Nominate getchoo
  candidates/getchoo.md
Labels: nomination, enough endorsements

#80 Nominate Gabriella439
  candidates/Gabriella439.md
Labels: nomination, enough endorsements

#46 Nominate djacu
  candidates/djacu.md
Labels: nomination, enough endorsements

#82 nominate mschwaig
  candidates/mschwaig.md
Labels: nomination, enough endorsements, nominee-accepted

#90 Nominate yu-re-ka
  candidates/yu-re-ka.md
Labels: nomination, enough endorsements, nominee-accepted

#92 Nominate nyabinary
  candidates/nyabinary.md
Labels: nomination, enough endorsements, nominee-accepted

#68 lovesegfault self-nominate
  candidates/lovesegfault.md
Labels: nomination, enough endorsements, nominee-accepted

#63 Nominate NotAShelf
  candidates/notashelf.md
Labels: nomination, enough endorsements, nominee-accepted
